// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Chapter { id: number, path: string, name: string, chapter_number: number, read: number, pages: number, comic_id: number, }