// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ChapterOrdering { id: number, comic_id: number, rank: number, regex: string, }