// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chapter } from "./Chapter";

export interface Comic { id: number, dir_path: string, name: string, cover_path: string | null, is_manga: boolean, chapters: Array<Chapter>, chapter_count: number | null, chapter_read: number | null, }